### ISSUE TITLE
Visual errors on Safari@IOS

### ISSUE THREAD

**Issue by avanc** [johakr/html5-slot-machine#30]
Some reels are blank at the almost end of the animation. If the animation is finished, the reels are again shown properly:
![image](https://user-images.githubusercontent.com/2905029/98545882-6df2ce80-2296-11eb-9f0b-6f8bb5fddaae.png)

Two right reels are missing. It depends on the time within the animation.

**Comment by avanc** [comment]
Similar behaviour on Chrome on Android. However, Firefox works flawless...

**Comment by johakr** [comment]
This commit https://github.com/johakr/html5-slot-machine/commit/8e5cd3917738781dcdba181f8789a2741be54d2f makes it somewhat better. At least no blanks anymore. But animation is still far from being smooth on Safari. I'm out of ideas for now. Any help welcome.

**Comment by dsc1025** [comment]
Thank you so much for your program helped me, but in the animation, "transform" consumes too much, you can use "top", can handle iPhone compatibility issues, I did this,

**Comment by Alimilad** [comment]
@dsc1025 can u share ur code

**Comment by SystemR** [comment]
Three things I've found with Safari bug:
1. On the `animation.onfinish` function you need to call `animation.cancel()` to reset the animation state. Otherwise Safari will keep the done state and not rerun the translate3d.
2. Safari doesn't seem to like `filter: blur()` in the animation keyframes. Removing this `filter: "blur(2px)"` line (and the next `filter: "blur(0px)"`) makes the spin animation work: https://github.com/johakr/html5-slot-machine/blob/b202c309f6b6f8975bd03c72f73d7e92dda79343/src/js/Reel.js#L15
3. However, adding `reelContainer.style.filter = 'blur(2px)';` at start and setting `reelContainer.style.filter = 'blur(0)';` inside the `animation.onfinish` makes the blur works. Just not keyframed.

Try this spin function:
```javascript
spin() {
  this.reelContainer.style.filter = 'blur(2px)';
  const animationPromise = new Promise((resolve) => {
    this.spinAnimation.onfinish = () => {
      this.reelContainer.style.filter = 'blur(0)';
      this.spinAnimation.cancel();
      resolve();
    };
  });

  ...

```

Also add `transition: filter 0.05s ease-in-out;` in the css to make the filter changes smooth.
